name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        timestamp=$(date +%s)
        docker login -u tux2603 -p $DOCKER_TOKEN
        docker build . --file Dockerfile --tag tux2603/helloworld:$timestamp
        docker image push tux2603/helloworld:$timestamp

